### ISSUE TITLE
should be reserved instead of reservated

### ISSUE THREAD

**Issue by tdermendzhieva** [KirilSivilov/Scalefocus-Bootcamp#1]
https://github.com/KirilSivilov/Scalefocus-Bootcamp/blob/7c433bd7bc948e80ed0773ed1ad9f4682608d32d/HotelReservationSystem/HotelReservationSystem/src/com/hotelReservationSystem/domain/reservation/ReservationImpl.java#L14

**Comment by KirilSivilov** [comment]
done
