### ISSUE TITLE
Rename getResertavionsData to getReservationsData

### ISSUE THREAD

**Issue by tdermendzhieva** [KirilSivilov/Scalefocus-Bootcamp#2]
https://github.com/KirilSivilov/Scalefocus-Bootcamp/blob/7c433bd7bc948e80ed0773ed1ad9f4682608d32d/HotelReservationSystem/HotelReservationSystem/src/com/hotelReservationSystem/interfaces/BookingSystem.java#L15

**Comment by KirilSivilov** [comment]
done
